FROM node:23-alpine

# Définition du répertoire de travail
WORKDIR /app

# Copie des fichiers package.json et package-lock.json
COPY package*.json ./

# Installation des dépendances
RUN npm ci --only=production

# Copier le reste des fichiers de l'application
COPY . .

# Générer le client Prisma
RUN npx prisma generate

# Création des dossiers nécessaires
RUN mkdir -p temp
RUN mkdir -p public/uploads/products

# Variables d'environnement par défaut
ENV PORT=3000
ENV NODE_ENV=production

# Exposition du port
EXPOSE ${PORT}

# Commande de démarrage
CMD ["sh", "-c", "npx prisma migrate deploy && node src/app.js"]